title: devuana's hideout
author: devuana
email: devuana at protonmail dot com
url: https://devuana.github.io
baseurl: ""
description: >
  my writings and ramblings

permalink: /:title

favicon: "logo.png"

theme_config:
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: :compressed
